[package]
name = "use_dynamic_libs"
version = "0.1.0"
authors = ["Stepan <stepannk@mail.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "*"

[build-dependencies]
cmake = "0.1.31"